DROP TABLE IF EXISTS MSA_Level;
CREATE TABLE MSA_Level AS
    SELECT MSA_MD, Loan_Type, Action_Type, COUNT(1) as NUM_BORROWERS, sum(Loan_Amount) as TOTAL_AMOUNT
    FROM HMDA_LAR
    WHERE Loan_Purpose = 1 AND Property_Type = 1
    GROUP BY MSA_MD, Loan_Type, Action_Type;

DROP TABLE IF EXISTS FHA_by_MSA;
CREATE TABLE FHA_by_MSA AS
    SELECT MSA_MD, SUM(NUM_BORROWERS) AS NUM_ALL, SUM(NUM_BORROWERS * (Loan_Type = 2)::int) AS NUM_FHA, SUM(TOTAL_AMOUNT) as AMT_ALL, SUM(TOTAL_AMOUNT * (Loan_Type = 2)::int) as AMT_FHA
    FROM MSA_Level
    WHERE ACTION_TYPE = 1
    GROUP BY MSA_MD;

ALTER TABLE FHA_by_MSA ADD PCT_NUM_FHA REAL;
UPDATE FHA_by_MSA
    SET PCT_NUM_FHA = NUM_FHA*100.0/NUM_ALL;

ALTER TABLE FHA_by_MSA ADD PCT_AMT_FHA REAL;
UPDATE FHA_by_MSA
    SET PCT_AMT_FHA = AMT_FHA*100.0/AMT_ALL;


\COPY (SELECT MSA_MD, NUM_ALL, NUM_FHA, PCT_NUM_FHA, AMT_ALL, AMT_FHA, PCT_AMT_FHA FROM FHA_by_MSA  ORDER BY PCT_AMT_FHA  DESC ) TO 'data/fha_by_msa.csv' WITH CSV
